CREATE TABLE IF NOT EXISTS _Teacher (
        _EMAIL TEXT PRIMARY KEY, 
        _FIO text,
        _PASS text
      );

CREATE TABLE IF NOT EXISTS _Group (
        _NAME VARCHAR PRIMARY KEY,
        _EMAIL_TEACHER text,
        CONSTRAINT zakrep FOREIGN KEY (_EMAIL_TEACHER) REFERENCES _Teacher (_EMAIL)
      );
      
CREATE TABLE IF NOT EXISTS _Student (
        _FIO text,
        _EMAIL TEXT PRIMARY KEY,
        _PASS text,
        _NUMBER integer,
        _GROUP VARCHAR,
        CONSTRAINT sostoit FOREIGN KEY(_GROUP) REFERENCES _Group(_NAME)
      );
      
CREATE TABLE IF NOT EXISTS _Quest (
        _NAME text PRIMARY KEY,
        _TEXT text,
        _VARIANTS text,
        _ANSER text
      );  

CREATE TABLE IF NOT EXISTS _Img (
	_ID bigserial PRIMARY KEY,
	_SRC text,
	_TEXT text
);

CREATE TABLE IF NOT EXISTS _Test (
	_NAME text PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS _SETUP(
	_QUEST text REFERENCES _Quest (_NAME) ON UPDATE CASCADE ON DELETE CASCADE,
	_TEST text REFERENCES _Test (_NAME) ON UPDATE CASCADE ON DELETE CASCADE,
	_NUMBER integer,
	CONSTRAINT _KEYS PRIMARY KEY (_QUEST, _TEST)
);

CREATE TABLE IF NOT EXISTS _SavedTest(
	_ID bigserial PRIMARY KEY,
	_NAME_TEST text,
	_ANSERS text,
	_UNCHECKED_ANSERS text,
	_EMAIL_STUDENT text,  
	_SCORE integer,
	CONSTRAINT sdelal FOREIGN KEY(_EMAIL_STUDENT) REFERENCES _Student(_EMAIL),
	CONSTRAINT est FOREIGN KEY(_NAME_TEST) REFERENCES _TEST(_NAME)
);

CREATE TABLE IF NOT EXISTS _Img_Quest(
	_QUEST text REFERENCES _Quest (_NAME) ON UPDATE CASCADE ON DELETE CASCADE,
	_IMG bigserial REFERENCES _Img (_ID) ON UPDATE CASCADE ON DELETE CASCADE, 
	CONSTRAINT _KEYIQ PRIMARY KEY (_QUEST, _IMG)
);

